#pragma once

#define _PMI_TEST_ 0
#define _PMI_TEST2_ 0

#define _PHASE3_VERBOSE_ 0
#define _PHASE3_BREAKS_ 0

#define _PHASE3_S0L_VERBOSE_ 0
#define _PHASE3_S0L_DECODE_ 0

#define _PHASE3_COMPUTE_FRAGMENTS_CACHE_ 1
#define _PHASE3_COMPUTE_FRAGMENTS_MARKERS_ 1
#define _PHASE3_COMPUTE_FRAGMENTS_OVERLAP_ 1
#define _PHASE3_COMPUTE_FRAGMENTS_PARTIALSOLUTION_ 1
#define _PHASE3_COMPUTE_FRAGMENTS_POSITION_ 1
#define _PHASE3_COMPUTE_FRAGMENTS_REVISE_ 1

#define _PHASE3_COMPUTE_LENGTH_GROWTH_ 1
#define _PHASE3_COMPUTE_LENGTH_LEXICON_ 1
#define _PHASE3_COMPUTE_LENGTH_TOTALPRODUCTION_ 1
#define _PHASE3_COMPUTE_LENGTH_TOTALLENGTH_ 1
#define _PHASE3_COMPUTE_LENGTH_SYMBIOLOGY_ 1

#define _PHASE3_COMPUTE_TOTALLENGTH_LENGTH_ 1
#define _PHASE3_COMPUTE_TOTALLENGTH_TOTALPRODUCTION_ 1
#define _PHASE3_COMPUTE_TOTALLENGTH_SYMBIOLOGY_ 1

#define _PHASE3_COMPUTE_GROWTH_FRAGMENT_ 1
#define _PHASE3_COMPUTE_GROWTH_LEXICON_ 1
#define _PHASE3_COMPUTE_GROWTH_SYMBIOLOGY_ 1
#define _PHASE3_COMPUTE_GROWTH_TOTALGROWTH_ 1
#define _PHASE3_COMPUTE_GROWTH_UAG_ 1

#define _PHASE3_COMPUTE_LOCALIZATION_ 1

#define _PHASE3_REVISE_FRAGMENTS_GROWTH_ 1
#define _PHASE3_REVISE_FRAGMENTS_UNDERGROWTH_ 1

#define _PHASE3_MAO_DISPLAY_ 1
#define _PHASE3_MAO_DISPLAY_NOFACTS_ 0

#define _PMI_PROBLEM_VERBOSE_ -1
#define _PMI_PROBLEM_TESTING_ 0
#define _PMI_PROBLEM_BREAKS_ 0
#define _PMI_PROBLEM_ERROR_CHECKING_ 0

#define _PMI_PROBLEM_DISPLAY_ANALYSIS_ 0
#define _PMI_PROBLEM_DISPLAY_FRAGMENTS_ 0
#define _PMI_PROBLEM_DISPLAY_FRAGMENT_ANALYSIS_ 0
#define _PMI_PROBLEM_DISPLAY_FRAGMENT_PARTIAL_SOLUTION_ 0
#define _PMI_PROBLEM_DISPLAY_RULES_ 0
#define _PMI_PROBLEM_DISPLAY_RULE_LENGTHS_ 0
#define _PMI_PROBLEM_DISPLAY_TABU_ 1
#define _PMI_PROBLEM_DISPLAY_MARKERS_ 0
#define _PMI_PROBLEM_DISPLAY_LEXICON_ 0
#define _PMI_PROBLEM_DISPLAY_EQUATIONS_ 0

#define _PMI_PROBLEM_CHEAT_ 0
#define _PMI_PROBLEM_KNOWN_CONSTANTS_ 1
#define _PMI_PROBLEM_ANALYZE_UAG_ 1
#define _PMI_PROBLEM_ANALYZE_FRAGMENTS_ 1
#define _PMI_PROBLEM_ANALYZE_LEXICON_ 0
#define _PMI_PROBLEM_ANALYZE_INFERENCE_ 1
#define _PMI_PROBLEM_PARTIAL_ROLLBACK_ 0
#define _PMI_PROBLEM_NO_TABU_MODULES_ 0
#define _PMI_PROBLEM_SEARCH_GA_ 1

#define _PMI_PROBLEM_FRAGMENTS_LOAD_ 0
#define _PMI_PROBLEM_FRAGMENTS_SAVE_ 0
#define _PMI_PROBLEM_LEXICON_LOAD_ 0
#define _PMI_PROBLEM_LEXICON_SAVE_ 0

#define _PMI_PROBLEM_SOLUTION_EVIDENCE_ 0
#define _PMI_PROBLEM_FIND_SUB_PROBLEM_VANISHING_VERBOSE_ 0
#define _PMI_PROBLEM_SHOW_CONSISTENCY_TABLE_ 0

#define _PMIT_D_V4_VERBOSE_ 0

#define _PMI_PROBLEM_MT_LEXICON_ 0 // DO NOT CHANGE THIS, THE INNER PROCESS IS ALREADY MT

