#include "stdafx.h"
#include "EvidenceFactoryV3.h"


EvidenceFactoryV3::EvidenceFactoryV3()
{
}


EvidenceFactoryV3::~EvidenceFactoryV3()
{
}

array<Int32, 2>^ EvidenceFactoryV3::Process(array<Int32>^ A, array<Int32, 2>^ R, Int32 Generations, Int32 NumSymbols, Int32 NumModules)
{
	array<Int32, 2>^ result;
	Int32 idx = 0;

	idx = 1;
	result = gcnew array<Int32, 2>(Generations + 1, NumSymbols);// +1 for the axiom
	for (size_t iSymbol = 0; iSymbol <= result->GetUpperBound(1); iSymbol++)
	{
		result[0, iSymbol] = A[iSymbol];
	}

	for (size_t iGen = 0; iGen < Generations; iGen++)
	{
		for (size_t iSymbol = 0; iSymbol <= result->GetUpperBound(1); iSymbol++)
		{
			Int32 count = 0;
			// Move the already produced constants up to the current generation
			if (iSymbol + 1 > NumModules)
			{
				result[iGen + 1, iSymbol] = result[iGen, iSymbol];
			}

			// Produce the symbols for each rule
			for (size_t iRule = 0; iRule <= R->GetUpperBound(0); iRule++)
			{
				result[iGen + 1, iSymbol] += result[iGen, iRule] * R[iRule, iSymbol];
			}
		}
	}

	return result;
}

array<WordXV3^>^ EvidenceFactoryV3::Process(WordXV3^ A, List<ProductionRuleV3^>^ R, Int32 Start, Int32 End, bool AxiomFirst)
{
	array<WordXV3^>^ result = gcnew array<WordXV3^>(End - Start);

	Int32 iGen = 0;

	if (AxiomFirst)
	{
		result[iGen] = gcnew WordXV3(A);
		iGen++;
	}

	for (size_t iGen = Start; iGen < End; iGen++)
	{
		WordXV3^ x = EvidenceFactoryV3::Process(A, R, iGen);

		//if (iGen == 0)
		//{
		//	x->SetSymbols("AA");
		//	x->ReInitialize();
		//}
		//if (iGen == 1)
		//{
		//	x->SetSymbols("AAAA");
		//	x->ReInitialize();
		//}
		//if (iGen == 2)
		//{
		//	x->SetSymbols("AABAAAAABAAABA");
		//	x->ReInitialize();
		//}
		//if (iGen == 3)
		//{
		//	x->SetSymbols("AABAAABABABABAABAAABAAAAAAABABABABAAAABAAABABABAA");
		//	x->ReInitialize();
		//}
		//if (iGen == 4)
		//{
		//	x->SetSymbols("AAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAAABBBABAAABBBABAAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAAABBBABAAAABBBABAAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAAABBBABAAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAAABBBABAAABBBABAAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAABBBABAAAABBBABAAAABBBABAAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAABBBABAAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAAABAABBBABAAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAAABBBABAAABBBABAAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAAABBBABAAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAABBBABAAABBBABAAABBBABAAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAAAAABAAAAABAAAAABAABBBABAAAAAABAAAAABAA");
		//	x->ReInitialize();
		//}

		A = x;
		result[iGen] = x;
	}

	return result;
}

WordXV3^ EvidenceFactoryV3::Process(WordXV3^ A, List<ProductionRuleV3^>^ R, Int32 T)
{
	WordXV3^ result = gcnew WordXV3();

	String^ x = "";
	Int32 iSymbol = 0;

	while (iSymbol < A->Length())
	{
		String^ s = A->GetSymbol(iSymbol);
		String^ Right = "";
		String^ Left = "";
		String^ Condition = "";
		Int32 toSkip = 1;

		int iRule = 0;
		bool found = false;
		bool fired = false;

		do
		{
			bool parametersSet = false;
			// TODO: convert to array of ints
			List<float>^ parameters = gcnew List<float>;

			if (R[iRule]->predecessor == s)
			{
				// TODO: Change this to get the proper context
				if (iSymbol > 0)
				{
					Left = A->GetSymbol(iSymbol - 1);
				}

				if (iSymbol < A->Length() - 1)
				{
					Right = A->GetSymbol(iSymbol + 1);
				}

				//// is there a parameter set?
				//if ((Right == "(") && (!parametersSet))
				//{
				//	Int32 done = false;
				//	Int32 iScan = 2;
				//	String^ tmp = A->GetSymbol(iSymbol + iScan);
				//	String^ values = "";

				//	while (!done)
				//	{
				//		if (tmp == ")")
				//		{
				//			done = true;
				//		}
				//		else
				//		{
				//			iScan++;
				//			tmp = A->GetSymbol(iSymbol + iScan);
				//		}
				//	}

				//	values = A->GetSymbolsNoCorrection(iSymbol + 2, iScan - 2);
				//	array<Char>^ seperatorComma = gcnew array<Char>{','};
				//	array<String^>^ v = values->Split(seperatorComma, System::StringSplitOptions::RemoveEmptyEntries);

				//	float valueF;

				//	for (size_t iValue = 0; iValue <= v->GetUpperBound(0); iValue++)
				//	{
				//		float::TryParse(v[iValue], valueF);
				//		parameters->Add(valueF);
				//	}

				//	parametersSet = true;
				//	toSkip = iScan + 1;
				//}

				// TODO: only do this dieRoll if stochastic is possible
				Int32 dieRoll = CommonGlobals::PoolInt(1, 100);

				String^ toAdd = R[iRule]->Produce(Left, Right, dieRoll, T, parameters);
				if (toAdd != ProductionRuleV3::WrongRule)
				{
					x += toAdd;
					fired = true;
					if (A->successorID != nullptr)
					{
						A->successorID[iSymbol] = R[iRule]->GetSuccessorID(toAdd);
					}
				}
			}

			iRule++; // try the next rule
		} while ((iRule< R->Count) && (!fired));

		// If no rule has fired then treat as a identify production
		if (!fired)
		{
			x += s;
		}

		// This is intended to keep the string of evidence from getting too long
		if (x->Length > ProductionRule::cMaxLength)
		{
			Console::WriteLine("Evidence Limit Exceeded");
			break;
		}

		iSymbol += toSkip;
	}

	result->SetSymbols(x);
	result->ReInitialize();

	return result;
}